### ISSUE TITLE
Unable to compile pyfcutils from scratch on macOS arm64

### ISSUE THREAD

**Issue by slwatkins** [legend-exp/pyfcutils#20]
I'm trying to compile `pyfcutils` from scratch to take a look at the underlying structure of the code and test some of the data that's being saved. However, I seem to be unable to compile the code.

The first error I was getting was

```
(py310) slw@pn2293687 pyfcutils % python setup.py install
Cython available, compiling .pyx sources
Compiling src/fcutils/fcutils.pyx because it changed.
[1/1] Cythonizing src/fcutils/fcutils.pyx

Error compiling Cython file:
------------------------------------------------------------
...
            p_addr[i] = pdp_addrs[i]
        for i in xrange(len(missing_pixels)):
            m_p[i] = missing_pixels[i]
        n_pdps = len(pdp_addrs)
        n_missing = len(missing_pixels)
        self.s = fclayout.FCLayoutCreate(p_addr, n_pdps, m_p, n_missing, CTA_MST_FLASHCAM_PROTOTYPE_LAYOUT)
                                                                        ^
------------------------------------------------------------

src/fcutils/fclayout.pyx:20:73: undeclared name not builtin: CTA_MST_FLASHCAM_PROTOTYPE_LAYOUT
Traceback (most recent call last):
  File "/Users/slw/Documents/repos/pyfcutils/setup.py", line 37, in <module>
    extensions = cythonize(extensions, language_level=3)
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/opt/anaconda3/envs/py310/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/fcutils/fcutils.pyx
```

So I tried changing the below line
https://github.com/legend-exp/pyfcutils/blob/df8a7c4b5adbac00bd4ac79d5cd7b2f2384f9273/src/fcutils/fclayout.pyx#L20
to:
```
self.s = fclayout.FCLayoutCreate(p_addr, n_pdps, m_p, n_missing, fclayout.CTA_MST_FLASHCAM_PROTOTYPE_LAYOUT)
``` 

However, now if I try to compile from a clean clone (using `python setup.py install`), I get the below error

```
ImportError: dlopen(/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pyfcutils-0.1.dev64+ga774906.d20230126-py3.10-macosx-10.9-x86_64.egg/fcutils.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_FCLayoutCreate)
```

This is all on Python 3.10, macOS 12.6.2, and Cython version 0.29.32. Happy to provide any more version info, seems odd!  Note if I try with `pip install .`, the same error shows up upon `import fcutils`.

**Comment by gipert** [comment]
@ssailer might have an idea?

**Comment by mwillers** [comment]
same thing on linux (conda w/ python 3.8 and cython-0.29.33)

**Comment by ssailer** [comment]
Sorry - somehow missed the first ping.

I just did a few tests and was able to recreate the error. Looks like it's something in the cython parsing step. It did get it to work when cython was not installed, as the the shipped `src/fcutils/fcutils.cpp` is used - it's overwritten with an empty file, when cython fails. 
I will have a look next week.

**Comment by mwillers** [comment]
added a PR #22
